name: Django CI/CD

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup SSH Key and Add to Agent
        run: |
          mkdir -p /home/runner/.ssh 
          echo "${{ secrets.KAWUNG_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add /home/runner/.ssh/id_rsa
        env:
          KAWUNG_SSH_KEY: ${{ secrets.KAWUNG_SSH_KEY }}

      - name: SSH to Kawung and deploy backend
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.KAWUNG_PORT }} ${{ secrets.KAWUNG_USERNAME }}@${{ secrets.KAWUNG_HOST }} << 'EOF'
          ssh admin@${{ secrets.VM_HOST }} << 'VM_EOF'
          cd backend
          git pull
          python manage.py migrate
          sudo systemctl restart gunicorn
          VM_EOF
          EOF
        env:
          KAWUNG_USERNAME: ${{ secrets.KAWUNG_USERNAME }}
          KAWUNG_HOST: ${{ secrets.KAWUNG_HOST }}
          KAWUNG_PORT: ${{ secrets.KAWUNG_PORT }}
          VM_HOST: ${{ secrets.VM_HOST }}
